### ISSUE TITLE
Source code files missing

### ISSUE THREAD

**Issue by isotherm** [MikeAlx/alphadrive#1]
I can't find any source code in any of the branches. It would be great to have this available for Linux, even if it is only proof of concept.

**Comment by MikeAlx** [comment]
Hi Kirk,

I had forgotten I'd ever set up a github entry for this! Looks like I
haven't touched the project since 2013.

I have attached a ZIP of the files I can find. Not sure if that's
everything - if not I can rummage on some old SD cards etc. I know I had
this running on a Raspberry Pi (under Debian Wheezy) back then. I've not
really dabbled in Raspberry Pi or C since.

I should say I'm not really a Linux guy or a C programmer (more of a Java
guy) - this was cobbled together largely from code kindly sent me by Mark
Moore, developer of Alphasync (Mac-based AlphaSmart sync software). He has
a github page here:
https://github.com/tSoniq

Looking at my readme file, there's a simple config file called
alphadrive.conf which basically defines some file storage locations, then a
file called 99-hid.rules which makes the OS trigger the software when an
Alphasmart is connected (in either HID keyboard mode or transfer mode). The
behaviour should be something like - when AlphaSmart is connected, switch
it into file transfer mode, then copy off all the files into the defined
store folder. Looks like there are some other parameters for version
management, but I can't remember if I ever implemented anything for that. I
was using it mainly to backup with Alphasmart in case the memory battery
failed.

Sorry to be vague, but it was a long time ago! Would be interested to know
if you do anything with this and where you get to. If you were intending to
do anything commercial with it, or to open source the code, I suggest you
should get in touch with Mark Moore first, since it's really mostly his
work. You can do what you like with my contributions, but I think they're
quite limited!

Best regards
Mike Alexander

**Comment by isotherm** [comment]
Thank you for the detailed explanation! Unfortunately, it looks like GitHub filtered the attachment out of your email. You might have to come on the GitHub site to attach them.

**Comment by MikeAlx** [comment]
OK, I've uploaded a pre-release ZIP. Should be showing under releases now. Direct link: [https://github.com/MikeAlx/alphadrive/releases/download/v1.0-beta/alphadrive.zip](https://github.com/MikeAlx/alphadrive/releases/download/v1.0-beta/alphadrive.zip)

Best regards
Mike

**Comment by isotherm** [comment]
Fantastic, thank you!
